#app:
#    resource: @AppBundle/Controller/
#    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

AppBundleV1:
    type: rest
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /api/v1